# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest

variables:
  MYSQL_ROOT_PASSWORD: test
  MYSQL_DATABASE: test_farm_manager
  MYSQL_USER: test
  MYSQL_PASSWORD: test_farm_manager
  NODE_ENV: test

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

setup_project:
  stage: build
  script:
    - yarn install

test_lint:
  stage: test
  script:
    - yarn lint

test_integration:
  script:
    - yarn test
