name: Shamba Manager Continuous Integration
on: [push, pull_request]

jobs:
  setup-and-tests:
    runs-on: ubuntu-latest

    container: node:20-alpine

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test_farm_manager
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          cache-dependency-path: ./package.json
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint

      - name: Integration tests
        run: pnpm test
        env:
          NODE_CONFIG_ENV: test-ci
