name: Shamba Manager Continuous Integration
on: [push, pull_request]

jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest

    container: node:lts

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test_farm_manager
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Integration tests
        run: yarn test
        env:
          NODE_ENV: test-ci
